// AUTH MODULE
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const REMEMBER_PASSWORD = 'REMEMBER_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'

// USERS MODULE
export const FETCH_USERS = 'FETCH_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const SELECTED_USER = 'SELECTED_USER'

export const NEWORDER = 'NEWORDER'
export const UPDATEORDER = 'UPDATEORDER'
export const DELETEORDER = 'DELETEORDER'

// ADMIN MODULE
export const NEWPIZZA = 'NEWPIZZA'
export const UPDATEPIZZA = 'UPDATEPIZZA'
export const DELETEPIZZA = 'DELETEPIZZA'

export const NEWFLAVOR = 'NEWFLAVOR'
export const UPDATEFLAVOR = 'UPDATEFLAVOR'
export const DELETEFLAVOR = 'DELETEFLAVOR'

export const NEWDRINK = 'NEWDRINK'
export const UPDATEDRINK = 'UPDATEDRINK'
export const DELETEDRINK = 'DELETEDRINK'

export const NEWADDITIONAL = 'NEWADDITIONAL'
export const UPDATEADDITIONAL = 'UPDATEADDITIONAL'
export const DELETEADDITIONAL = 'DELETEADDITIONAL'

export const NEWSIZE = 'NEWSIZE'
export const UPDATESIZE = 'UPDATESIZE'
export const DELETESIZE = 'DELETESIZE'
